workflows:

    sample-workflow:

        name: Codemagic Sample Workflow

        max_build_duration: 120

        instance_type: mac_mini_m2

    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier:  com.testbongame.app